---
- name: Destroy infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Destroy Terraform resources
      community.general.terraform:
        project_path: "{{ playbook_dir }}/terraform"
        state: absent
