---
- name: Atualizar DNS - CRIAR registro A e PTR
  hosts: localhost
  gather_facts: false

  vars:
    host_ip:
    hostname:

    dns_server: "192.168.100.11"
    dns_zone: "aroque.com.br"
    dns_reverse_zone: "100.168.192.in-addr.arpa"
    dns_key_name: "ansible-key"
    dns_key_secret: 
    dns_key_algorithm: "hmac-sha256"

  collections:
    - community.general

  tasks:
    - name: Criar registro A no DNS
      community.general.nsupdate:
        server: "{{ dns_server }}"
        zone: "{{ dns_zone }}"
        record: "{{ hostname.split('.')[0] }}"
        type: A
        value: "{{ host_ip }}"
        ttl: 300
        key_name: "{{ dns_key_name }}"
        key_secret: "{{ dns_key_secret }}"
        key_algorithm: "{{ dns_key_algorithm }}"

    - name: Criar registro PTR no DNS reverso
      community.general.nsupdate:
        server: "{{ dns_server }}"
        zone: "{{ dns_reverse_zone }}"
        record: "{{ host_ip.split('.')[-1] }}"
        type: PTR
        value:  "{{ hostname }}."
        ttl: 300
        key_name: "{{ dns_key_name }}"
        key_secret: "{{ dns_key_secret }}"
        key_algorithm: "{{ dns_key_algorithm }}"

    - name: Debug variable host_ip
      ansible.builtin.debug:
        var: host_ip

    - name: Debug variable hostname
      ansible.builtin.debug:
        var: hostname

    - name: Export host_ip to another job template
      ansible.builtin.set_stats:
        data:
          host_ip: "{{ host_ip }}"
          hostname: "{{ hostname }}"
