- name: Automate SNOW - Change Request Create
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm

  vars:
    sn_short_description: "Change Open Via Ansible"
    sn_description: "Change Open Via Ansible"
    sn_impact_value: "low"
    sn_urgency_value: "low"
    sn_category_value: "network"

  tasks:
    - name: Create change request
      servicenow.itsm.change_request:
        state: present   # 🔥 CORREÇÃO AQUI
        instance:
          host: "{{ snow_instance_host }}"
          username: "{{ snow_username_value }}"
          password: "{{ snow_password_value }}"
        short_description: "{{ sn_short_description }}"
        description: "{{ sn_description }}"
        impact: "{{ sn_impact_value }}"
        urgency: "{{ sn_urgency_value }}"
        category: "{{ sn_category_value }}"
      register: new_change_request

    - name: Set change request number
      set_fact:
        sn_change_request_number: "{{ new_change_request.record.number }}"

    - name: Debug change request number
      ansible.builtin.debug:
        var: new_change_request.record.number

    - name: Set change request number
      set_stats:
        data:
          sn_change_request_number: "{{ new_change_request.record.number }}"
